# Generated by Django 4.2.11 on 2024-06-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SistemCerdas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_sistem_cerdas', models.FileField(upload_to='sistem_cerdas/')),
            ],
        ),
    ]
